config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
  	member do
      get :approve
      get :rejected
  	end
  end

  resources :admin, only:[:index, :update] do
  	member do
      get :operator
      get :supervisor
  	end
  end

  devise_for :users

  root "tickets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
      user = User.new
    end

    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :supervisor
      can [:create, :read, :edit, :rejected, :approve], Ticket
    elsif user.has_role? :operator
      can [:create, :read, :destroy], Ticket, user_id: user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  resourcify
  belongs_to :user

  enum status: { submitted: 0, approved: 1, rejected: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets

  after_create :assign_role

  def assign_role
    add_role(:operator)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize
  before_action :authenticate_user!

  # Lista todos o usuarios
  def index
    @users = User.all
  end

  # Adiciona Role Supervisor
  def supervisor
    remove_last_role
    @user.add_role(:supervisor)
    redirect_to '/admin', notice: 'Role Supervisor was successfully updated.'
  end

  # Adiciona Role Operator
  def operator
    remove_last_role
    @user.add_role(:operator)
    redirect_to '/admin', notice: 'Role Operator was successfully updated.'
  end


  private

  # Autoriza somente acesso com role admin page /admin
  def authorize
    if !current_user.has_role? :admin
      redirect_to root_url
    end
  end

  # Remove a ultima role do usuario
  def remove_last_role
    @user = User.find(params[:id])
    @user.roles = []
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.where(user: current_user)
               unless current_user.has_role?(:admin) || current_user.has_role?(:supervisor)
    @ability = Ability.new(current_user)
  end

  def approve
    set_ticket
    @ticket.approved!
    redirect_to root_path, notice: "The Ticket has been approved"
  end

  def rejected
    set_ticket
    @ticket.rejected!
    redirect_to root_path, notice: "The Ticket has been rejected"
  end

  def new
    @ticket = current_user.tickets.build
  end

  def create
    @ticket = current_user.tickets.build(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end
end
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :status, :user_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_label status
    status_span_generator status
  end

  def status_span_generator status
    case status
      when 'submitted'
       content_tag(:span, status.titleize, class: "blue-text text-darken-4")
      when 'approved'
       content_tag(:span, status.titleize, class: "green-text text-darken-4")
      when 'rejected'
       content_tag(:span, status.titleize, class: "red-text text-darken-4")
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Area Admin</h3>

<table class="centered striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.roles.last.name %></td>
          <td><%= link_to 'Make Supervisor', supervisor_admin_path(user),
                                             class: "btn deep-purple darken-4" %></td>

          <td><%= link_to 'Make Operator', operator_admin_path(user),
                                           class: "btn light-blue darken-4" %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>CronoTimer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>
      <%= if !current_user.nil?
            current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ') '
          end
      %>
    </p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Tickets</h4>

<%= link_to new_ticket_path, method: :get, class: "btn-floating waves-light blue" do %>
  <i class="material-icons">fiber_new</i>
<% end %>


<br>

    <div class="row">
      <% @tickets.each do |ticket| %>
      <% if @ability.can? :read, Ticket, user_id: current_user.id %>
        <div class="col s4 l4 m4">
          <div class="card light-blue lighten-2">
            <div class="card-content white-text">
              <span class="card-title"><td><%= ticket.title %></td></span>
                <p><%= status_label ticket.status %></p>  <p><%= ticket.user.email %></p>
            </div>
            <div class="card-action">
              <% if @ability.can? :edit, Ticket %>
                <td> <%= link_to 'rejected',
                        rejected_ticket_path(ticket),
                        class: "btn waves-effect waves-light red" %></td>

                <td> <%= link_to 'Approve',
                        approve_ticket_path(ticket),
                        class: "btn waves-effect waves-light green" %></td>
              <% end %>
              <hr>
              <% if @ability.can? :destroy, Ticket %>
                <td>
                  <%= link_to ticket, method: :delete,
                               class: "btn-floating halfway-fab waves-effect waves-light red",
                               data: { confirm: "Tem certeza que deseja Excluir" } do %>
                    <i class="material-icons">delete</i>
                  <% end %>
                </td>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <% end %>
    </div>

<%= link_to 'Logout', destroy_user_session_path, method: :delete %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket.user %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>